---
title: Running the matching on the server
tags: [server]
---

This tutorial shows you how to run the matching pipeline in a confidential
server on GCP. Before you attempt this tutorial, please ensure you have worked
through our [architecture set-up](01-setup-server.qmd), and both of your
data-owning parties have successfully [uploaded their data](02-client.qmd) to
GCP.

::: {.callout-important}
You only need to follow this tutorial if you are going to be the administrator
of the linkage. See our client set-up tutorial if you're looking to get your
data linked privately by another party.
:::

## Running the pipeline

Once your parties have uploaded their data, you can run the pipeline
server by executing the following commands in your terminal:

```bash
export $(grep 'PPRL_PROJECT' .env | xargs -0)
gcloud compute instances create pprl-tee \
    --confidential-compute \
    --shielded-secure-boot \
    --maintenance-policy=TERMINATE \
    --scopes=cloud-platform \
    --zone=$PPRL_PROJECT_ZONE \
    --image-project=confidential-space-images \
    --image-family=confidential-space \
    --service-account=run-confidential-vm@$PPRL_PROJECT_NAME.iam.gserviceaccount.com \
    --metadata="^~^tee-image-reference=$PPRL_PROJECT_REGION-docker.pkg.dev/$PPRL_PROJECT_NAME/pprl-repo/pprl-server-image:latest"
```

## Closing down

Once the data linkage has taken place, the instance should stop running
automatically. run the following command to delete the
virtual machine:

```bash
echo "Y" | gcloud compute instances delete projects/$PPRL_PROJECT_NAME/zones/$PPRL_PROJECT_ZONE/instances/pprl-tee
```
