name: Publish documentation

on:
    workflow_dispatch:
    push:
        branches: main

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2
            - name: Install Python and dependencies
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
                cache: "pip"
            - name: Build API reference
              run: |
                python -m pip install ".[docs]"
                python -m quartodoc build
            - name: Render and publish
              uses: quarto-dev/quarto-actions/publish@v2
              with:
                target: gh-pages
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                PARTY_1_PROJECT: pprl-party-1
                PARTY_1_KEY_VERSION: 1
                PARTY_2_PROJECT: pprl-party-2
                PARTY_2_KEY_VERSION: 1
                WORKLOAD_AUTHOR_PROJECT: pprl-party-1
                WORKLOAD_AUTHOR_PROJECT_REGION: europe-west2
                WORKLOAD_OPERATOR_PROJECT: pprl-party-2
                WORKLOAD_OPERATOR_PROJECT_ZONE: europe-west2-c
